// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEkCp8TkISV2xqFD99UzZ5s8JJA1FKP6U',
    appId: '1:337140327418:web:fdf09db6af3d9024723a43',
    messagingSenderId: '337140327418',
    projectId: 'social-app-b99c3',
    authDomain: 'social-app-b99c3.firebaseapp.com',
    storageBucket: 'social-app-b99c3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALxQ49tX7An110UL_OeYz2Fi-yLm39PyY',
    appId: '1:337140327418:android:8d63ee6b53a7adf6723a43',
    messagingSenderId: '337140327418',
    projectId: 'social-app-b99c3',
    storageBucket: 'social-app-b99c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk7EiJpasP4T4D_e9JZng4I-9ssxmyzp4',
    appId: '1:337140327418:ios:2cead65c0e7a9e94723a43',
    messagingSenderId: '337140327418',
    projectId: 'social-app-b99c3',
    storageBucket: 'social-app-b99c3.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk7EiJpasP4T4D_e9JZng4I-9ssxmyzp4',
    appId: '1:337140327418:ios:2cead65c0e7a9e94723a43',
    messagingSenderId: '337140327418',
    projectId: 'social-app-b99c3',
    storageBucket: 'social-app-b99c3.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEkCp8TkISV2xqFD99UzZ5s8JJA1FKP6U',
    appId: '1:337140327418:web:342fd16ae419f51e723a43',
    messagingSenderId: '337140327418',
    projectId: 'social-app-b99c3',
    authDomain: 'social-app-b99c3.firebaseapp.com',
    storageBucket: 'social-app-b99c3.firebasestorage.app',
  );
}
